### ISSUE TITLE
Hello! Select served model from list below is No data. How do I use it?

### ISSUE THREAD

**Issue by SmilQe** [supervisely-ecosystem/apply-owl-vit-to-images-project#6]
![image](https://github.com/supervisely-ecosystem/apply-owl-vit-to-images-project/assets/35120911/85e60d91-7b90-4563-ac13-41f5f64488fb)

**Comment by iwatkot** [comment]
Hello! You need to deploy a model using the Serve OWL-ViT app: https://ecosystem.supervisely.com/apps/serve-owl-vit
And then connect to the deployed model (it will appear in the Connect to model section).
